name: Deploy my app

on:
  push:
    branches: [ general-devel ] # Set the branch that will trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '14.x'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        branch: general-devel # Set the branch to deploy to
        folder: ./build # Change this to the build directory of your app
        github-token: ${{ secrets.GITHUB_TOKEN }}
